### Update the @externalIP variable with the external IP adress of your AKS cluster
@externalIP=

### Check the Dapr sidecar is running
GET http://{{externalIP}}/ports

### Make a new order
POST http://{{externalIP}}/neworder
Content-Type: application/json

< sample.json

### Check last order state

GET http://{{externalIP}}/order